apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: config-server
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: config-server
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/LyleXu/spring-petclinic-microservices/tree/azure/spring-petclinic-config-server
      ref:
        branch: main
